# fly.toml app configuration file generated for haru-be on 2026-05-13T22:33:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haru-be'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
